name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - edited
      # let’s see if those exist
      - milestoned
      - demilestoned

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, '|' ) }}

jobs:
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
      - if: github.event.pull_request.milestone == null && contains( env.LABELS, 'no milestone' ) == false
        run: exit 1
